name: Publish package

on:
  workflow_dispatch:
  push:
    branches:
      - feature/setup-cicd # Just for testing

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18.18.2'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Run build
        run: npm run build
      - name: Run package
        id: run-package
        run: echo "filename=$(npm pack -q)" >> "$GITHUB_OUTPUT"
      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: 'tgz-package'
          path: ${{ steps.run-package.outputs.filename }}
          if-no-files-found: error
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-22.04
    needs:
      - build
    defaults:
      run:
        working-directory: /tmp
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: 'tgz-package'
          path: 'read-vietnamese-number.tgz'
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18.18.2'
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: Run publish
        run: npm publish read-vietnamese-number.tgz --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
